const lesson = [
  {
    id: 1,
    title: "Math",
    location: "London",
    price: 100000,
    image: "images/math.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 2,
    title: "English",
    location: "London",
    price: 100000,
    image: "images/english.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 3,
    title: "Chemo",
    location: "London",
    price: 100000,
    image: "images/chemo.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 4,
    title: "Physics",
    location: "London",
    price: 100000,
    image: "images/physics.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 5,
    title: "Robotics",
    location: "London",
    price: 100000,
    image: "images/robotics.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 6,
    title: "History",
    location: "London",
    price: 100000,
    image: "images/history.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 7,
    title: "French",
    location: "London",
    price: 100000,
    image: "images/french.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 8,
    title: "Animation",
    location: "London",
    price: 100000,
    image: "images/animation.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 9,
    title: "Music",
    location: "London",
    price: 100000,
    image: "images/music.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 10,
    title: "Design",
    location: "London",
    price: 100000,
    image: "images/design.jpg",
    space: 5,
    availableSpace: 5,
  },
  {
    id: 11,
    title: "Art",
    location: "London",
    price: 100000,
    image: "images/art.jpg",
    space: 5,
    availableSpace: 5,
  },
];
